---
image: androidsdk/android-30
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/MasonAmerica/watch-health-app.git
    - git fetch origin
    - git checkout -b public origin/public
    - git rebase origin/master
    #- echo .gitlab-ci.yml >>.gitignore
   # - git push -u github public:master --force
    #- git push github $CI_COMMIT_TAG
    - git push -u github public:master --force
    #- git tag v$CI_COMMIT_TAG
    #- git push -u github public:master v$CI_COMMIT_TAG
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+/