---
image: androidsdk/android-30
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/MasonAmerica/watch-health-app.git
    - git fetch origin
    - git checkout -b master
    - git push -u github master --force